---
- hosts: serverCentosUTU
  become: yes
  become_user: root 
  tasks:
  - name: Bajando apache
    service:
      name: httpd
      state: stopped

  - name: Deshabilitando firewall para https
    firewalld:
      service: https
      permanent: yes
      state: disabled

      
