---
- hosts: serverCentosUTU
  become: yes
  become_user: root
  tasks:
  - name: instalando Apache
    yum:
      name: httpd
      disable_gpg_check: yes
      state: latest                                

