---
- hosts: serverCentosUTU
  become: yes
  become_user: root 
  tasks:
  - name: Levantando apache
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Deshabilitando firewall para https
    firewalld:
      service: https
      permanent: yes
      state: enabled
 
